name: Code audit

on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    name: Code audit

    steps:
      - name: ‚¨á Git checkout
        uses: actions/checkout@v2

      - name: ‚ùì Check if .editorconfig exists
        uses: andstor/file-existence-action@v1
        with:
          files: ".editorconfig"
          allow_failure: true

      - name: ‚úÖ EditorConfig validation
        uses: snow-actions/eclint@v1.0.1

      - name: üôà Ensure node_modules is ignored by Git
        uses: dkershner6/gitignore-parser@v1
        with:
          must_deny: "node_modules"

      - name: üíæ Install modules
        run: npm ci

      - name: Environments
        run: npm run env
        env:
          API_URL: ${{ secrets.API_URL }}
          USERS_PATH: ${{ secrets.USERS_PATH }}
          LOGIN_PATH: ${{ secrets.LOGIN_PATH }}
          REGISTER_PATH: ${{ secrets.REGISTER_PATH }}

      - name: üîç ESLint validation
        run: npx eslint --ignore-path .gitignore . --max-warnings 0

      - name: üìè Check commit message length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^[^#].{10,74}"
          error: "The commit message length must be between 10 and 74"
          excludeDescription: "true" # optional: this excludes the description body of a pull request
          excludeTitle: "true" # optional: this excludes the title of a pull request
          checkAllCommitMessages: "true" # optional: this checks all commits associated with a pull request

